stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: analytics-flow-engine
timeout: 60
notification:
  recipients:
  - recipient: '#ccses-rancher'
    notifier: c-lrbcp:n-zxhj6
  condition:
  - Success
  - Changed
  - Failed
